name: GitHub Actions Rector Test
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: setup
        uses: shivammathur/setup-php@v2
        with:
            php-version: '8.1'
            extensions: mbstring, intl, ldap,fileinfo, xsl
      - name: checkout
        uses: actions/checkout@v2
      - name: Install PHP
        run: php composer.phar update
      - name: Rector
        run: vendor/bin/rector process src -vvv